
export const MODULE = {
    ADD: 'MODULE/ADD',
    GET: 'MODULE/GET',
    GET_BY_ID: 'MODULE/GET_BY_ID',
    UPDATE_BY_ID: 'MODULE/UPDATE_BY_ID',
    DELETE_BY_ID: 'MODULE/DELETE_BY_ID',
    CLEAR: 'MODULE/CLEAR',
};

export const PHASE = {
    ADD: 'PHASE/ADD',
    GET: 'PHASE/GET',
    GET_BY_ID: 'PHASE/GET_BY_ID',
    UPDATE_BY_ID: 'PHASE/UPDATE_BY_ID',
    DELETE_BY_ID: 'PHASE/DELETE_BY_ID',
    CLEAR: 'PHASE/CLEAR',
};

export const PRACTICE = {
    ADD: 'PRACTICE/ADD',
    GET: 'PRACTICE/GET',
    GET_BY_ID: 'PRACTICE/GET_BY_ID',
    UPDATE_BY_ID: 'PRACTICE/UPDATE_BY_ID',
    DELETE_BY_ID: 'PRACTICE/DELETE_BY_ID',
    CLEAR: 'PRACTICE/CLEAR',
};

export const COMMON = {
    SHOW_DIALOG: 'COMMON/SHOW_DIALOG',
    HIDE_DIALOG: 'COMMON/HIDE_DIALOG',
    UNMOUNT_DIALOG: 'COMMON/UNMOUNT_DIALOG',
};
